---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-repo-guestbook
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/argoproj/argocd-example-apps.git
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: guestbook-microservice
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm-guestbook/
      sourceRef:
        kind: GitRepository
        name: git-repo-guestbook
      valuesFiles: 
        - ./helm-guestbook/values.yaml
        - ./helm-guestbook/values-production.yaml
  test:
    enable: true