backend:
  replicaCount: 1
  image:
    repository: gcr.io/heptio-images/ks-guestbook-demo
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.1"

webapp:
  replicaCount: 1